import { NextResponse } from 'next/server';
import { getDb } from '../../../db';
import { contactLists, contacts, teamMembers } from '../../../db/schema';
import { listContacts } from '../../../db/queries';
import { routeLeadForList } from '../../../db/assignment';
import { notifySeller } from '../../../lib/lead-email';
import { eq } from 'drizzle-orm';
import { requireApiUser } from '../../chatgpt-auth';

export async function GET(request: Request) { if (!await requireApiUser()) return NextResponse.json({ error: 'Não autorizado' }, { status: 401 }); const listId = new URL(request.url).searchParams.get('listId'); if (!listId) return NextResponse.json([]); return NextResponse.json(await listContacts(listId)); }
export async function POST(request: Request) { const current = await requireApiUser(); if (!current) return NextResponse.json({ error: 'Não autorizado' }, { status: 401 }); const body = await request.json() as Record<string, string>; if (!body.listId || !(body.name?.trim() || body.email?.trim() || body.phone?.trim())) return NextResponse.json({ error: 'Dados insuficientes' }, { status: 400 }); const route = await routeLeadForList(body.listId); let seller = route.seller; if (body.assignedUserId && current.role === 'manager') { const [chosen] = await getDb().select({ id: teamMembers.id, name: teamMembers.name, email: teamMembers.email }).from(teamMembers).where(eq(teamMembers.id, body.assignedUserId)).limit(1); seller = chosen ?? seller; } const now = new Date(); const record = { id: crypto.randomUUID(), listId: body.listId, stageId: route.stageId, assignedUserId: seller?.id ?? null, name: body.name?.trim() ?? '', email: body.email?.trim().toLowerCase() ?? '', phone: body.phone?.trim() ?? '', company: body.company?.trim() ?? '', notes: body.notes?.trim() ?? '', source: 'manual', createdAt: now, updatedAt: now }; await getDb().insert(contacts).values(record); if (seller) { const [list] = await getDb().select({ name: contactLists.name }).from(contactLists).where(eq(contactLists.id, body.listId)).limit(1); await notifySeller({ contactId: record.id, seller, lead: record, listName: list?.name || 'Contatos' }).catch(() => undefined); } return NextResponse.json(record, { status: 201 }); }
