"use client";
import {ChangeEvent,FormEvent,useCallback,useEffect,useMemo,useState} from "react";
type Contact={id:number;name:string;email:string;phone:string;city:string;source:string;listId:number|null;listName:string;createdAt:string};
type LeadList={id:number;name:string;token:string;active:boolean;createdAt:string};
type Log={id:number;provider:string;status:string;email:string;message:string;receivedAt:string};
type Data={people:Contact[];lists:LeadList[];webhookLogs:Log[]};
const empty:Data={people:[],lists:[],webhookLogs:[]};
const fmt=(v:string)=>new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"});
const initials=(v:string)=>v.split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase();
const csvCell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;

export default function Home(){
 const [data,setData]=useState<Data>(empty),[selected,setSelected]=useState<number|"all">("all"),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[toast,setToast]=useState("");
 const [contact,setContact]=useState<Contact|null|undefined>(undefined),[listModal,setListModal]=useState<LeadList|null|undefined>(undefined);
 const flash=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2700)};
 const load=useCallback(async()=>{try{const r=await fetch("/api/crm",{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}catch(e){flash(e instanceof Error?e.message:"Falha ao carregar")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function api(method:string,body:unknown,msg?:string){const r=await fetch("/api/crm",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j.error);await load();if(msg)flash(msg);return j}
 const current=selected==="all"?null:data.lists.find(x=>x.id===selected)||null;
 const contacts=useMemo(()=>data.people.filter(p=>(selected==="all"||p.listId===selected)&&`${p.name} ${p.email} ${p.phone} ${p.city}`.toLowerCase().includes(search.toLowerCase())),[data.people,selected,search]);
 const webhookUrl=current&&typeof window!=="undefined"?`${window.location.origin}/api/webhook/greatpages/${current.token}`:"";
 async function saveContact(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=Object.fromEntries(new FormData(e.currentTarget));const list=data.lists.find(x=>x.id===Number(form.listId));form.listName=list?.name||"";try{if(contact)await api("PATCH",{entity:"people",id:contact.id,data:form},"Contato atualizado");else await api("POST",{entity:"people",data:form},"Contato adicionado");setContact(undefined)}catch(e){flash(e instanceof Error?e.message:"Erro ao salvar")}}
 async function saveList(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{if(listModal)await api("PATCH",{entity:"lists",id:listModal.id,data:{name:f.name,active:f.active==="on"}},"Lista atualizada");else{const j=await api("POST",{entity:"lists",data:{name:f.name}},"Lista criada");setSelected(j.row.id)}setListModal(undefined)}catch(e){flash(e instanceof Error?e.message:"Erro ao salvar")}}
 async function removeContact(p:Contact){if(confirm(`Excluir o contato ${p.name}?`))try{await api("DELETE",{entity:"people",id:p.id},"Contato excluído")}catch(e){flash(e instanceof Error?e.message:"Erro ao excluir")}}
 async function removeList(l:LeadList){if(confirm(`Excluir a lista “${l.name}”? Os contatos serão mantidos.`))try{await api("DELETE",{entity:"lists",id:l.id},"Lista excluída");setSelected("all")}catch(e){flash(e instanceof Error?e.message:"Erro ao excluir")}}
 function exportCsv(){const rows=[["Nome","E-mail","Telefone","Cidade","Origem","Lista","Cadastro"],...contacts.map(p=>[p.name,p.email,p.phone,p.city,p.source,p.listName,p.createdAt])];const blob=new Blob(["\ufeff"+rows.map(r=>r.map(csvCell).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`contatos-${current?.name||"todos"}.csv`;a.click();URL.revokeObjectURL(a.href)}
 async function importCsv(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(selected==="all"){flash("Selecione uma lista antes de importar");e.target.value="";return}try{const lines=(await file.text()).replace(/^\ufeff/,"").split(/\r?\n/).filter(Boolean),sep=lines[0].includes(";")?";":",";const headers=lines.shift()!.split(sep).map(x=>x.replaceAll('"',"").trim().toLowerCase());let total=0;for(const line of lines){const cells=line.split(sep).map(x=>x.trim().replace(/^"|"$/g,"").replaceAll('""','"'));const get=(...k:string[])=>{const i=headers.findIndex(x=>k.includes(x));return i<0?"":cells[i]||""};const name=get("nome","name"),email=get("e-mail","email","e mail");if(!name||!email)continue;const r=await fetch("/api/crm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({entity:"people",data:{name,email,phone:get("telefone","phone","whatsapp","celular"),city:get("cidade","city"),source:get("origem","source")||"Importação CSV",listId:selected,listName:current?.name}})});if(r.ok)total++}await load();flash(`${total} contatos importados`)}catch{flash("Não foi possível importar o CSV")}finally{e.target.value=""}}
 async function testWebhook(){try{const r=await fetch(webhookUrl,{method:"POST",headers:{"content-type":"application/json","x-crm-test":"true"},body:JSON.stringify({nome:"Contato de teste",email:`teste-${Date.now()}@institutofortuna.com.br`,telefone:"(11) 99999-9999"})}),j=await r.json();if(!r.ok)throw new Error(j.error);await load();flash("Integração funcionando corretamente")}catch(e){flash(e instanceof Error?e.message:"Falha no teste")}}
 return <div className="shell"><aside><div className="brand"><img src="/forttuna-logo.png" alt="Instituto Fortuna"/><span>CRM DE CONTATOS</span></div><button className={selected==="all"?"nav active":"nav"} onClick={()=>setSelected("all")}><i>◎</i><span>Todos os contatos<small>{data.people.length} cadastrados</small></span></button><div className="side-title"><span>LISTAS DE CAPTAÇÃO</span><button onClick={()=>setListModal(null)}>＋</button></div><div className="list-nav">{data.lists.map(l=><button key={l.id} className={selected===l.id?"nav active":"nav"} onClick={()=>setSelected(l.id)}><i>≡</i><span>{l.name}<small>{data.people.filter(p=>p.listId===l.id).length} contatos</small></span><em className={l.active?"dot on":"dot"}/></button>)}</div><div className="help"><b>Integração GreatPages</b><p>Cada lista possui uma URL própria para receber leads automaticamente.</p></div></aside><main><header className="top"><div><span>INSTITUTO FORTUNA</span><h1>{current?.name||"Todos os contatos"}</h1><p>{current?"Administre os contatos e a integração desta lista.":"Visão consolidada das suas listas de captação."}</p></div><button className="primary" onClick={()=>setContact(null)}>＋ Novo contato</button></header>{loading?<div className="loading"><i/><b>Carregando contatos…</b></div>:<>
 <section className="stats"><article><span>TOTAL DE CONTATOS</span><strong>{contacts.length}</strong><small>no filtro atual</small></article><article><span>LISTAS ATIVAS</span><strong>{data.lists.filter(x=>x.active).length}</strong><small>prontas para receber leads</small></article><article><span>VIA GREATPAGES</span><strong>{data.people.filter(x=>x.source.startsWith("GreatPages")).length}</strong><small>leads recebidos</small></article></section>
 {current&&<section className="integration"><div className="integration-head"><div className="hook">↯</div><div><span>WEBHOOK EXCLUSIVO DA LISTA</span><h2>Integração com GreatPages</h2><p>Copie esta URL e cole no campo de webhook da sua página.</p></div><b className={current.active?"status on":"status"}>{current.active?"● ATIVA":"● DESATIVADA"}</b></div><div className="url"><code>{webhookUrl}</code><button onClick={()=>navigator.clipboard.writeText(webhookUrl).then(()=>flash("URL copiada"))}>Copiar URL</button></div><div className="integration-actions"><button onClick={testWebhook}>Testar integração</button><button onClick={()=>setListModal(current)}>Editar lista</button><button className="danger" onClick={()=>removeList(current)}>Excluir lista</button></div></section>}
 {!data.lists.length&&<section className="empty-list"><div>≡</div><h2>Crie sua primeira lista</h2><p>Uma URL exclusiva para o GreatPages será criada automaticamente.</p><button className="primary" onClick={()=>setListModal(null)}>＋ Criar primeira lista</button></section>}
 <section className="contacts"><div className="panel-head"><div><h2>Contatos</h2><p>{contacts.length} registros encontrados</p></div><div className="tools"><label className="search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar nome, e-mail ou telefone"/></label><label className="secondary upload">↑ Importar CSV<input type="file" accept=".csv,text/csv" onChange={importCsv}/></label><button className="secondary" onClick={exportCsv} disabled={!contacts.length}>↓ Exportar CSV</button></div></div><div className="table"><div className="row table-head"><span>CONTATO</span><span>TELEFONE</span><span>CIDADE</span><span>ORIGEM</span><span>CADASTRO</span><span/></div>{contacts.map(p=><div className="row" key={p.id}><span className="person"><i>{initials(p.name)}</i><b>{p.name}<small>{p.email}</small></b></span><span>{p.phone||"—"}</span><span>{p.city||"—"}</span><span><em className="source">{p.source||"Manual"}</em></span><span>{fmt(p.createdAt)}</span><span className="row-actions"><button onClick={()=>setContact(p)}>Editar</button><button onClick={()=>removeContact(p)}>Excluir</button></span></div>)}{!contacts.length&&<div className="no-results"><b>Nenhum contato nesta lista</b><span>Adicione, importe um CSV ou envie pelo webhook.</span></div>}</div></section>
 {current&&<section className="recent"><div><h2>Últimos recebimentos</h2><p>Registros recentes da integração.</p></div>{data.webhookLogs.filter(x=>x.provider.includes(current.name)).slice(0,5).map(l=><article key={l.id}><i className={l.status==="sucesso"?"ok":"bad"}>{l.status==="sucesso"?"✓":"!"}</i><span><b>{l.email||l.message}</b><small>{l.message}</small></span><time>{fmt(l.receivedAt)}</time></article>)}{!data.webhookLogs.some(x=>x.provider.includes(current.name))&&<small className="muted">Nenhum webhook recebido ainda.</small>}</section>}</>}</main>
 {contact!==undefined&&<Modal title={contact?"Editar contato":"Adicionar contato"} close={()=>setContact(undefined)}><form onSubmit={saveContact} className="form-grid"><label>Nome completo<input name="name" required defaultValue={contact?.name}/></label><label>E-mail<input name="email" type="email" required defaultValue={contact?.email}/></label><label>Telefone / WhatsApp<input name="phone" defaultValue={contact?.phone}/></label><label>Cidade<input name="city" defaultValue={contact?.city}/></label><label>Origem<input name="source" defaultValue={contact?.source||"Cadastro manual"}/></label><label>Lista<select name="listId" defaultValue={contact?.listId??(selected==="all"?"":selected)}><option value="">Sem lista</option>{data.lists.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><div className="modal-actions"><button type="button" onClick={()=>setContact(undefined)}>Cancelar</button><button className="primary">Salvar contato</button></div></form></Modal>}
 {listModal!==undefined&&<Modal title={listModal?"Editar lista":"Criar nova lista"} close={()=>setListModal(undefined)}><form onSubmit={saveList} className="list-form"><label>Nome da lista<input name="name" required autoFocus defaultValue={listModal?.name} placeholder="Ex.: Palestra Osasco"/></label>{listModal&&<label className="check"><input name="active" type="checkbox" defaultChecked={listModal.active}/> Lista ativa para receber leads</label>}<p>A URL segura será criada automaticamente.</p><div className="modal-actions"><button type="button" onClick={()=>setListModal(undefined)}>Cancelar</button><button className="primary">{listModal?"Salvar alterações":"Criar lista"}</button></div></form></Modal>}{toast&&<div className="toast">✓ {toast}</div>}</div>
}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="modal"><header><div><span>CRM INSTITUTO FORTUNA</span><h2>{title}</h2></div><button onClick={close}>×</button></header>{children}</section></div>}
