import { createSupabaseAdminClient } from './supabase/admin';

function escape(value: string) { return value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] || char)); }

export async function sendFollowUpAlert(input: { taskId: string; contactId: string; seller: { name: string; email: string }; lead: { name: string; email: string; phone: string }; title: string; notes: string; dueDate: string }) {
  const key = process.env.RESEND_API_KEY; if (!key || !input.seller.email) return false;
  const when = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short', timeZone: 'America/Sao_Paulo' }).format(new Date(input.dueDate));
  const text = `Olá, ${input.seller.name}.\n\nVocê tem um follow-up pendente no Capta CRM.\n\nLead: ${input.lead.name || 'Sem nome'}\nAção: ${input.title}\nPrazo: ${when}\nTelefone: ${input.lead.phone || 'Não informado'}\nE-mail: ${input.lead.email || 'Não informado'}${input.notes ? `\nObservações: ${input.notes}` : ''}\n\nAcesse sua agenda comercial no CRM para acompanhar.`;
  const response = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', 'Idempotency-Key': `capta-follow-up-${input.taskId}` }, body: JSON.stringify({ from: process.env.CAPTA_EMAIL_FROM || 'Luciana França <luciana.franca@mail.forttuna.com.br>', to: [input.seller.email], reply_to: process.env.CAPTA_EMAIL_REPLY_TO || 'luciana.franca@forttuna.com.br', subject: `Follow-up pendente: ${input.lead.name || 'lead do CRM'}`, html: `<div style="font-family:Arial,sans-serif;background:#f4f3f8;padding:28px"><div style="max-width:560px;margin:auto;background:#fff;border-radius:14px;padding:28px"><b style="color:#5b5bd6">CAPTA CRM · FOLLOW-UP</b><h2 style="color:#26262b">${escape(input.title)}</h2><p>Olá, ${escape(input.seller.name)}. Você tem um acompanhamento pendente.</p><p><strong>Lead:</strong> ${escape(input.lead.name || 'Sem nome')}<br><strong>Prazo:</strong> ${escape(when)}<br><strong>Telefone:</strong> ${escape(input.lead.phone || 'Não informado')}<br><strong>E-mail:</strong> ${escape(input.lead.email || 'Não informado')}</p>${input.notes ? `<p><strong>Observações:</strong> ${escape(input.notes)}</p>` : ''}<p>Acesse a tela <strong>Minha agenda comercial</strong> para concluir ou reagendar.</p></div></div>`, text }) });
  const result = await response.json().catch(() => ({})) as { id?: string }; const admin = createSupabaseAdminClient();
  await admin.from('crm_email_delivery_logs').insert({ id: crypto.randomUUID(), contact_id: input.contactId, kind: 'follow_up_alert', recipient: input.seller.email, status: response.ok ? 'sent' : 'failed', provider_message_id: result.id || null, error_code: response.ok ? null : `resend_${response.status}` });
  return response.ok;
}
