type LeadEmail = { contactId: string; seller: { name: string; email: string }; lead: { name: string; email: string; phone: string; company: string }; listName: string };

function escape(value: string) { return value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] || char)); }

export async function notifySeller(input: LeadEmail) {
  const key = process.env.RESEND_API_KEY; if (!key) return;
  const name = escape(input.lead.name || 'Novo lead'); const seller = escape(input.seller.name || 'Vendedor');
  const response = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', 'Idempotency-Key': `capta-lead-${input.contactId}` }, body: JSON.stringify({ from: process.env.CAPTA_EMAIL_FROM || 'Capta CRM <onboarding@resend.dev>', to: [input.seller.email], reply_to: process.env.CAPTA_EMAIL_REPLY_TO || 'micbrava@gmail.com', subject: `Novo lead atribuído: ${input.lead.name || input.lead.email || input.lead.phone}`, html: `<!doctype html><html><body style="margin:0;background:#f4f3f8;font-family:Arial,Helvetica,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td align="center" style="padding:32px 16px"><table width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;background:#ffffff;border-radius:14px"><tr><td style="padding:28px"><p style="font-size:12px;color:#6d5dfb;font-weight:700">CAPTA CRM</p><h1 style="font-size:24px;color:#23241f">Olá, ${seller}</h1><p style="font-size:15px;line-height:1.6;color:#5e6058">Um novo lead foi atribuído a você na lista <strong>${escape(input.listName)}</strong>.</p><table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f7f6fb;border-radius:10px"><tr><td style="padding:18px"><strong style="font-size:17px;color:#292a25">${name}</strong><p style="font-size:13px;line-height:1.7;color:#65675f">${escape(input.lead.email || 'Sem e-mail')}<br>${escape(input.lead.phone || 'Sem telefone')}<br>${escape(input.lead.company || 'Sem empresa')}</p></td></tr></table><p style="font-size:13px;color:#777970;margin-top:22px">Acesse o Capta CRM para iniciar o atendimento.</p></td></tr></table></td></tr></table></body></html>`, text: `Olá, ${input.seller.name}. Novo lead em ${input.listName}: ${input.lead.name}, ${input.lead.email}, ${input.lead.phone}, ${input.lead.company}. Acesse o Capta CRM para iniciar o atendimento.` }) });
  if (!response.ok) throw new Error(`Resend ${response.status}`);
}
