import { NextResponse } from 'next/server';
import { eq } from 'drizzle-orm';
import { getDb } from '../../../../db';
import { contactLists, contacts, teamMembers } from '../../../../db/schema';
import { requireApiUser } from '../../../chatgpt-auth';
import { notifySeller } from '../../../../lib/lead-email';

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { const current = await requireApiUser(); if (!current) return NextResponse.json({ error: 'Não autorizado' }, { status: 401 }); const { id } = await params; const body = await request.json() as Record<string, string | null>; const db = getDb(); const [before] = await db.select().from(contacts).where(eq(contacts.id, id)).limit(1); const values: Partial<typeof contacts.$inferInsert> = { updatedAt: new Date() }; if (body.name !== undefined) values.name = body.name?.trim() ?? ''; if (body.email !== undefined) values.email = body.email?.trim().toLowerCase() ?? ''; if (body.phone !== undefined) values.phone = body.phone?.trim() ?? ''; if (body.company !== undefined) values.company = body.company?.trim() ?? ''; if (body.notes !== undefined) values.notes = body.notes?.trim() ?? ''; if (body.stageId !== undefined) values.stageId = body.stageId || null; if (body.assignedUserId !== undefined && current.role === 'manager') values.assignedUserId = body.assignedUserId || null; await db.update(contacts).set(values).where(eq(contacts.id, id)); if (before && values.assignedUserId && values.assignedUserId !== before.assignedUserId) { const [[seller], [list]] = await Promise.all([db.select({ id: teamMembers.id, name: teamMembers.name, email: teamMembers.email }).from(teamMembers).where(eq(teamMembers.id, values.assignedUserId)).limit(1), db.select({ name: contactLists.name }).from(contactLists).where(eq(contactLists.id, before.listId)).limit(1)]); if (seller) await notifySeller({ contactId: id, seller, lead: { name: values.name ?? before.name, email: values.email ?? before.email, phone: values.phone ?? before.phone, company: values.company ?? before.company }, listName: list?.name || 'Contatos' }).catch(() => undefined); } return NextResponse.json({ ok: true }); }
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { if (!await requireApiUser()) return NextResponse.json({ error: 'Não autorizado' }, { status: 401 }); const { id } = await params; await getDb().delete(contacts).where(eq(contacts.id, id)); return NextResponse.json({ ok: true }); }
