import { eq } from "drizzle-orm";
import { getDb } from "../../../../../db";
import { leadLists, people, webhookLogs, webhookSettings } from "../../../../../db/schema";
function pick(p:Record<string,unknown>,keys:string){for(const k of keys.split(",").map(x=>x.trim()))if(p[k]!=null&&String(p[k]).trim())return String(p[k]).trim();return "";}
export async function POST(request:Request,{params}:{params:Promise<{token:string}>}){const db=getDb();let payload:Record<string,unknown>={};const {token}=await params;try{
 const list=(await db.select().from(leadLists).where(eq(leadLists.token,token)))[0];if(!list||!list.active)return Response.json({ok:false,error:"Lista inexistente ou desativada"},{status:404});
 const content=request.headers.get("content-type")??"";payload=content.includes("application/json")?await request.json() as Record<string,unknown>:Object.fromEntries((await request.formData()).entries());
 if(request.headers.get("x-crm-test")==="true"){await db.insert(webhookLogs).values({provider:`GreatPages · ${list.name}`,status:"sucesso",email:String(payload.email??""),message:`Teste concluído: lista ${list.name} → ${list.targetFunnel} / ${list.targetStage}`,payloadJson:JSON.stringify(payload)});return Response.json({ok:true,test:true,message:"Webhook funcionando",list:list.name,funnel:list.targetFunnel,stage:list.targetStage});}
 const settings=(await db.select().from(webhookSettings).limit(1))[0];if(settings?.secret){const supplied=request.headers.get("x-webhook-secret")||String(payload.webhook_secret??"");if(supplied!==settings.secret){await db.insert(webhookLogs).values({provider:`GreatPages · ${list.name}`,status:"rejeitado",message:"Segredo inválido",payloadJson:JSON.stringify(payload)});return Response.json({ok:false,error:"Não autorizado"},{status:401});}}
 const map=settings?JSON.parse(settings.mappingJson||"{}"):{};const name=pick(payload,map.name||"name,nome,full_name,nome_completo"),email=pick(payload,map.email||"email,e-mail").toLowerCase();if(!name||!email){await db.insert(webhookLogs).values({provider:`GreatPages · ${list.name}`,status:"erro",email,message:"Nome ou e-mail ausente",payloadJson:JSON.stringify(payload)});return Response.json({ok:false,error:"Nome e e-mail são obrigatórios",received_fields:Object.keys(payload)},{status:400});}
 const source=pick(payload,map.source||"utm_source,origem,source")||list.name,dealValue=Number(pick(payload,map.dealValue||"value,valor,deal_value")||0);
 const [person]=await db.insert(people).values({name,email,phone:pick(payload,map.phone||"phone,telefone,whatsapp,celular"),city:pick(payload,map.city||"city,cidade"),source:`GreatPages · ${source}`,funnel:list.targetFunnel,stage:list.targetStage,nextOffer:pick(payload,map.nextOffer||"next_offer,proxima_oferta"),dealValue,listId:list.id,listName:list.name}).onConflictDoUpdate({target:people.email,set:{name,phone:pick(payload,map.phone||"phone,telefone,whatsapp,celular"),city:pick(payload,map.city||"city,cidade"),source:`GreatPages · ${source}`,funnel:list.targetFunnel,stage:list.targetStage,dealValue,listId:list.id,listName:list.name}}).returning();
 await db.insert(webhookLogs).values({provider:`GreatPages · ${list.name}`,status:"sucesso",email,message:`Lead entrou na lista ${list.name} e no funil ${list.targetFunnel}`,payloadJson:JSON.stringify(payload)});return Response.json({ok:true,message:"Lead recebido",person_id:person.id,list:list.name,funnel:list.targetFunnel,stage:list.targetStage},{status:201});
 }catch(error){await db.insert(webhookLogs).values({provider:`GreatPages · ${token}`,status:"erro",message:error instanceof Error?error.message:"Falha",payloadJson:JSON.stringify(payload)});return Response.json({ok:false,error:error instanceof Error?error.message:"Falha no webhook"},{status:500});}}
export async function GET(_:Request,{params}:{params:Promise<{token:string}>}){const {token}=await params;const list=(await getDb().select().from(leadLists).where(eq(leadLists.token,token)))[0];return list?Response.json({ok:true,list:list.name,target:{funnel:list.targetFunnel,stage:list.targetStage},active:list.active}):Response.json({ok:false,error:"Lista não encontrada"},{status:404});}
