import { asc, desc, eq, sql } from "drizzle-orm";
import { getDb } from "../../../db";
import { events, funnelStages, interactions, leadLists, people, products, purchases, salesFunnels, webhookLogs, webhookSettings } from "../../../db/schema";
type Entity="people"|"events"|"products"|"purchases"|"interactions"|"funnels"|"stages"|"webhookSettings"|"lists";
const err=(e:unknown)=>Response.json({error:e instanceof Error?e.message:"Erro inesperado"},{status:500});
const defaults=["Palestras","Imersão presencial","Formação de terapeuta presencial","Certificação de terapeuta online","Certificação","Live","Aula secreta","Venda direta via anúncio pago","Indicações","Mentoria","Atendimento individual"];
const defaultStages=["Novo lead","Contato realizado","Qualificado","Proposta enviada","Negociação","Venda realizada"];
async function ensureDefaults(){const db=getDb();const current=await db.select().from(salesFunnels).limit(1);if(current.length)return;for(let i=0;i<defaults.length;i++){const [f]=await db.insert(salesFunnels).values({name:defaults[i],sortOrder:i}).returning();await db.insert(funnelStages).values(defaultStages.map((name,j)=>({funnelId:f.id,name,sortOrder:j})));}await db.insert(webhookSettings).values({provider:"GreatPages",targetFunnel:defaults[0],targetStage:defaultStages[0],mappingJson:JSON.stringify({name:"name,nome,full_name,nome_completo",email:"email,e-mail",phone:"phone,telefone,whatsapp,celular",city:"city,cidade",source:"utm_source,origem,source",dealValue:"value,valor,deal_value"})});}
export async function GET(){try{await ensureDefaults();const db=getDb();const [p,e,pr,b,i,f,s,w,l,lists]=await Promise.all([db.select().from(people).orderBy(desc(people.createdAt)),db.select().from(events).orderBy(desc(events.eventDate)),db.select().from(products).orderBy(desc(products.id)),db.select().from(purchases).orderBy(desc(purchases.purchasedAt)),db.select().from(interactions).orderBy(desc(interactions.occurredAt)),db.select().from(salesFunnels).orderBy(asc(salesFunnels.sortOrder)),db.select().from(funnelStages).orderBy(asc(funnelStages.sortOrder)),db.select().from(webhookSettings).limit(1),db.select().from(webhookLogs).orderBy(desc(webhookLogs.receivedAt)).limit(20),db.select().from(leadLists).orderBy(desc(leadLists.createdAt))]);return Response.json({people:p,events:e,products:pr,purchases:b,interactions:i,funnels:f,stages:s,webhookSettings:w[0]||null,webhookLogs:l,lists});}catch(e){return err(e)}}
export async function POST(request:Request){try{const {entity,data}=await request.json() as {entity:Entity;data:Record<string,unknown>};const db=getDb();
 if(entity==="people"){const name=String(data.name??"").trim(),email=String(data.email??"").trim().toLowerCase(),listId=data.listId?Number(data.listId):null,listName=String(data.listName??"");if(!name||!email)return Response.json({error:"Nome e e-mail são obrigatórios"},{status:400});const values={name,email,phone:String(data.phone??""),city:String(data.city??""),source:String(data.source??"Cadastro manual"),status:"Lead",funnel:listName||"Lista de contatos",stage:"Novo lead",owner:"Equipe Fortuna",listId,listName};const [row]=await db.insert(people).values(values).onConflictDoUpdate({target:people.email,set:values}).returning();return Response.json({row},{status:201});}
 if(entity==="events"){const [row]=await db.insert(events).values({title:String(data.title),city:String(data.city??"Online"),eventDate:String(data.eventDate),capacity:Number(data.capacity??0),registrations:Number(data.registrations??0),revenue:Number(data.revenue??0),status:String(data.status??"Planejado")}).returning();return Response.json({row},{status:201});}
 if(entity==="products"){const [row]=await db.insert(products).values({name:String(data.name),category:String(data.category),price:Number(data.price??0),active:true}).returning();return Response.json({row},{status:201});}
 if(entity==="purchases"){const personId=Number(data.personId),amount=Number(data.amount??0),productName=String(data.productName);const [row]=await db.insert(purchases).values({personId,productId:data.productId?Number(data.productId):null,productName,amount,status:String(data.status??"Pago"),purchasedAt:String(data.purchasedAt??new Date().toISOString())}).returning();if(row.status==="Pago")await db.update(people).set({revenue:sql`${people.revenue} + ${amount}`,status:"Cliente"}).where(eq(people.id,personId));await db.insert(interactions).values({personId,type:"Compra",title:productName,amount});return Response.json({row},{status:201});}
 if(entity==="interactions"){const [row]=await db.insert(interactions).values({personId:Number(data.personId),type:String(data.type),title:String(data.title),amount:Number(data.amount??0),occurredAt:String(data.occurredAt??new Date().toISOString())}).returning();return Response.json({row},{status:201});}
 if(entity==="funnels"){const order=(await db.select().from(salesFunnels)).length;const [row]=await db.insert(salesFunnels).values({name:String(data.name),sortOrder:order}).returning();await db.insert(funnelStages).values(defaultStages.slice(0,4).map((name,j)=>({funnelId:row.id,name,sortOrder:j})));return Response.json({row},{status:201});}
 if(entity==="stages"){const funnelId=Number(data.funnelId),order=(await db.select().from(funnelStages).where(eq(funnelStages.funnelId,funnelId))).length;const [row]=await db.insert(funnelStages).values({funnelId,name:String(data.name),sortOrder:order}).returning();return Response.json({row},{status:201});}
 if(entity==="lists"){const name=String(data.name??"").trim();if(!name)return Response.json({error:"Nome da lista é obrigatório"},{status:400});const token=`lista-${crypto.randomUUID().replaceAll("-","").slice(0,20)}`;const [row]=await db.insert(leadLists).values({name,token,targetFunnel:name,targetStage:"Novo lead",active:true}).returning();return Response.json({row},{status:201});}
 return Response.json({error:"Entidade inválida"},{status:400});}catch(e){return err(e)}}
export async function PATCH(request:Request){try{const {entity,id,data}=await request.json() as {entity:Entity;id:number;data:Record<string,unknown>};const db=getDb();
 if(entity==="people"){const listId=data.listId?Number(data.listId):null,listName=String(data.listName??"");const [row]=await db.update(people).set({...(data.name!==undefined&&{name:String(data.name)}),...(data.email!==undefined&&{email:String(data.email).toLowerCase()}),...(data.phone!==undefined&&{phone:String(data.phone)}),...(data.city!==undefined&&{city:String(data.city)}),...(data.source!==undefined&&{source:String(data.source)}),...(data.listId!==undefined&&{listId,listName,funnel:listName||"Lista de contatos"})}).where(eq(people.id,id)).returning();return Response.json({row});}
 if(entity==="events"){const [row]=await db.update(events).set({...(data.title!==undefined&&{title:String(data.title)}),...(data.city!==undefined&&{city:String(data.city)}),...(data.eventDate!==undefined&&{eventDate:String(data.eventDate)}),...(data.capacity!==undefined&&{capacity:Number(data.capacity)}),...(data.registrations!==undefined&&{registrations:Number(data.registrations)}),...(data.revenue!==undefined&&{revenue:Number(data.revenue)}),...(data.status!==undefined&&{status:String(data.status)})}).where(eq(events.id,id)).returning();return Response.json({row});}
 if(entity==="products"){const [row]=await db.update(products).set({...(data.name!==undefined&&{name:String(data.name)}),...(data.category!==undefined&&{category:String(data.category)}),...(data.price!==undefined&&{price:Number(data.price)}),...(data.active!==undefined&&{active:Boolean(data.active)})}).where(eq(products.id,id)).returning();return Response.json({row});}
 if(entity==="funnels"){const old=(await db.select().from(salesFunnels).where(eq(salesFunnels.id,id)))[0];const name=String(data.name);await db.update(salesFunnels).set({name}).where(eq(salesFunnels.id,id));if(old)await db.update(people).set({funnel:name}).where(eq(people.funnel,old.name));return Response.json({ok:true});}
 if(entity==="stages"){const old=(await db.select().from(funnelStages).where(eq(funnelStages.id,id)))[0];const name=String(data.name);await db.update(funnelStages).set({name}).where(eq(funnelStages.id,id));if(old)await db.update(people).set({stage:name}).where(eq(people.stage,old.name));return Response.json({ok:true});}
 if(entity==="webhookSettings"){const current=(await db.select().from(webhookSettings).limit(1))[0];const values={targetFunnel:String(data.targetFunnel),targetStage:String(data.targetStage),secret:String(data.secret??""),active:Boolean(data.active),mappingJson:String(data.mappingJson),updatedAt:new Date().toISOString()};if(current)await db.update(webhookSettings).set(values).where(eq(webhookSettings.id,current.id));else await db.insert(webhookSettings).values({...values,provider:"GreatPages"});return Response.json({ok:true});}
 if(entity==="lists"){const old=(await db.select().from(leadLists).where(eq(leadLists.id,id)))[0];if(!old)return Response.json({error:"Lista não encontrada"},{status:404});const name=data.name!==undefined?String(data.name):old.name;await db.update(leadLists).set({name,targetFunnel:name,...(data.active!==undefined&&{active:Boolean(data.active)})}).where(eq(leadLists.id,id));if(data.name!==undefined)await db.update(people).set({listName:name,funnel:name}).where(eq(people.listId,id));return Response.json({ok:true});}
 return Response.json({error:"Atualização não suportada"},{status:400});}catch(e){return err(e)}}
export async function DELETE(request:Request){try{const {entity,id}=await request.json() as {entity:Entity;id:number};const db=getDb();if(entity==="people")await db.delete(people).where(eq(people.id,id));else if(entity==="lists"){await db.update(people).set({listId:null,listName:"",funnel:"Lista de contatos"}).where(eq(people.listId,id));await db.delete(leadLists).where(eq(leadLists.id,id));}else return Response.json({error:"Exclusão inválida"},{status:400});return Response.json({ok:true});}catch(e){return err(e)}}
