'use client';

import { useCallback, useEffect, useState } from 'react';

type Pipeline = { id: string; name: string; color: string; stages: { id: string; name: string }[] };
type ContactList = { id: string; name: string; segment: string; color: string; pipelineId: string | null; contactCount: number };

export default function AutomationPanel({ lists, reloadLists, flash, openPipelines }: { lists: ContactList[]; reloadLists: () => Promise<void>; flash: (message: string) => void; openPipelines: () => void }) {
  const [pipelines, setPipelines] = useState<Pipeline[]>([]); const [saving, setSaving] = useState('');
  const load = useCallback(async () => { const response = await fetch('/api/pipelines'); setPipelines(await response.json() as Pipeline[]); }, []);
  useEffect(() => { load(); }, [load]);
  async function assign(listId: string, pipelineId: string | null) { setSaving(listId); await fetch(`/api/lists/${listId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pipelineId }) }); await reloadLists(); setSaving(''); flash('Direcionamento salvo. Os próximos contatos seguirão esta automação.'); }
  return <div className="automation-screen"><section className="automation-hero"><div className="automation-icon">↗</div><div><span className="eyebrow">AUTOMAÇÃO DE ENTRADA</span><h2>Direcionamento das listas</h2><p>Escolha para qual funil cada lista enviará seus novos contatos. Webhooks e importações continuam funcionando normalmente.</p></div><button className="secondary" onClick={openPipelines}>Gerenciar funis</button></section><section className="routing-table"><header><div><strong>Lista de captação</strong><span>Contatos atuais</span><span>Destino automático</span><span>Primeira etapa</span></div></header>{lists.map((list) => { const pipeline = pipelines.find((item) => item.id === list.pipelineId); return <div className="routing-row" key={list.id}><div className="routing-list-name"><span style={{ background: list.color }} /> <div><strong>{list.name}</strong><small>{list.segment || 'Sem segmento'}</small></div></div><span className="routing-count">{list.contactCount}</span><label><select value={list.pipelineId || ''} disabled={saving === list.id} onChange={(event) => assign(list.id, event.target.value || null)}><option value="">Não direcionar</option>{pipelines.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><span className={pipeline ? 'destination-stage active' : 'destination-stage'}>{pipeline?.stages[0]?.name || '—'}</span></div>; })}{!lists.length && <div className="routing-empty"><h3>Nenhuma lista criada</h3><p>Crie uma lista na aba Contatos para configurar o direcionamento.</p></div>}</section><div className="automation-note"><span>i</span><p><strong>Como funciona:</strong> quando um lead chegar pelo Great Pages, cadastro manual ou importação CSV, ele será criado na lista e também colocado na primeira etapa do funil escolhido.</p></div></div>;
}
