'use client';

import { useCallback, useEffect, useState } from 'react';
type Stage = { id: string; name: string }; type Pipeline = { id: string; name: string; stages: Stage[] }; type Member = { id: string; name: string; email: string; role: string; active: boolean };
type ContactList = { id: string; name: string; segment: string; color: string; pipelineId: string | null; routingStageId: string | null; assignmentMode: 'manual' | 'fixed' | 'round_robin'; fixedSellerId: string | null; rotationMemberIds: string[]; contactCount: number };

export default function AutomationPanel({ lists, reloadLists, flash, openPipelines }: { lists: ContactList[]; reloadLists: () => Promise<void>; flash: (message: string) => void; openPipelines: () => void }) {
  const [pipelines, setPipelines] = useState<Pipeline[]>([]); const [members, setMembers] = useState<Member[]>([]); const [saving, setSaving] = useState(''); const [rotationDraft, setRotationDraft] = useState<Record<string, string[]>>({});
  const load = useCallback(async () => { const [p, m] = await Promise.all([fetch('/api/pipelines'), fetch('/api/team')]); setPipelines(await p.json() as Pipeline[]); setMembers(await m.json() as Member[]); }, []); useEffect(() => { load(); }, [load]); useEffect(() => { setRotationDraft(Object.fromEntries(lists.map((list) => [list.id, list.rotationMemberIds || []]))); }, [lists]);
  const sellers = members.filter((member) => member.role === 'sales' && member.active);
  async function save(listId: string, values: Record<string, unknown>) { setSaving(listId); const response = await fetch(`/api/lists/${listId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); await reloadLists(); setSaving(''); flash(response.ok ? 'Automação salva com sucesso.' : 'Não foi possível salvar a automação.'); }
  function toggleSeller(listId: string, memberId: string) { setRotationDraft((current) => { const selected = current[listId] || []; return { ...current, [listId]: selected.includes(memberId) ? selected.filter((id) => id !== memberId) : [...selected, memberId] }; }); }

  return <div className="automation-screen"><section className="automation-hero"><div className="automation-icon">↗</div><div><span className="eyebrow">AUTOMAÇÃO DE ENTRADA</span><h2>Destino e responsáveis</h2><p>Defina para onde cada lead vai e qual vendedor assume o atendimento.</p></div><button className="secondary" onClick={openPipelines}>Gerenciar funis</button></section>
    <h3 className="automation-section-title">1. Direcionar para funil e etapa</h3><section className="routing-table"><header><div><strong>Lista de captação</strong><span>Contatos</span><span>Funil de destino</span><span>Etapa de entrada</span></div></header>{lists.map((list) => { const pipeline = pipelines.find((item) => item.id === list.pipelineId); const stages = pipeline?.stages || []; return <div className="routing-row" key={list.id}><div className="routing-list-name"><span style={{ background: list.color }} /><div><strong>{list.name}</strong><small>{list.segment || 'Sem segmento'}</small></div></div><span className="routing-count">{list.contactCount}</span><label><select value={list.pipelineId || ''} disabled={saving === list.id} onChange={(event) => { const pipelineId = event.target.value || null; save(list.id, { pipelineId, routingStageId: pipelines.find((item) => item.id === pipelineId)?.stages[0]?.id || null }); }}><option value="">Não direcionar</option>{pipelines.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label><select value={list.routingStageId || stages[0]?.id || ''} disabled={!pipeline || saving === list.id} onChange={(event) => save(list.id, { routingStageId: event.target.value || null })}><option value="">Escolha a etapa</option>{stages.map((stage) => <option value={stage.id} key={stage.id}>{stage.name}</option>)}</select></label></div>; })}</section>
    <h3 className="automation-section-title seller-title">2. Atribuir vendedor</h3><section className="seller-automation-grid">{lists.map((list) => <article className="seller-rule" key={list.id}><header><i style={{ background: list.color }} /><div><strong>{list.name}</strong><small>Responsável pelos próximos leads</small></div></header><div className="assignment-modes"><button className={list.assignmentMode === 'manual' ? 'active' : ''} onClick={() => save(list.id, { assignmentMode: 'manual', fixedSellerId: null })}>Manual</button><button className={list.assignmentMode === 'fixed' ? 'active' : ''} onClick={() => save(list.id, { assignmentMode: 'fixed', fixedSellerId: list.fixedSellerId || sellers[0]?.id || null })}>Vendedor fixo</button><button className={list.assignmentMode === 'round_robin' ? 'active' : ''} onClick={() => save(list.id, { assignmentMode: 'round_robin', fixedSellerId: null })}>Alternadamente</button></div>{list.assignmentMode === 'manual' && <p className="assignment-help">O gestor escolhe o vendedor diretamente ao editar o lead.</p>}{list.assignmentMode === 'fixed' && <label className="seller-select">Vendedor responsável<select value={list.fixedSellerId || ''} onChange={(event) => save(list.id, { fixedSellerId: event.target.value || null })}><option value="">Escolha um vendedor</option>{sellers.map((seller) => <option value={seller.id} key={seller.id}>{seller.name} · {seller.email}</option>)}</select></label>}{list.assignmentMode === 'round_robin' && <div className="rotation-members"><span>Marque os vendedores que participam do rodízio</span>{sellers.map((seller) => <label key={seller.id} className={(rotationDraft[list.id] || []).includes(seller.id) ? 'selected' : ''}><input type="checkbox" checked={(rotationDraft[list.id] || []).includes(seller.id)} onChange={() => toggleSeller(list.id, seller.id)} /><i>{seller.name.slice(0, 1).toUpperCase()}</i><span>{seller.name}<small>{seller.email}</small></span></label>)}{!sellers.length && <p>Cadastre integrantes com o perfil Vendedor na aba Equipe.</p>}<button className="save-rotation" disabled={saving === list.id || !(rotationDraft[list.id] || []).length} onClick={() => save(list.id, { assignmentMode: 'round_robin', fixedSellerId: null, rotationMemberIds: rotationDraft[list.id] || [] })}>{saving === list.id ? 'Salvando…' : `Salvar rodízio · ${(rotationDraft[list.id] || []).length} selecionados`}</button></div>}</article>)}</section>
    <div className="automation-note"><span>i</span><p>No rodízio, o próximo vendedor é reservado de forma atômica, evitando que leads simultâneos sejam entregues à mesma pessoa. O vendedor atribuído recebe um alerta por e-mail.</p></div></div>;
}
