'use client';

import { ChangeEvent, FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import PipelineBoard from './pipeline-board';
import AutomationPanel from './automation-panel';
import './pipeline.css';
import './enhancements.css';
import './polish.css';

type ContactList = { id: string; name: string; segment: string; color: string; webhookToken: string; pipelineId: string | null; routingStageId: string | null; contactCount: number };
type Contact = { id: string; listId: string; name: string; email: string; phone: string; company: string; notes: string; source: string; createdAt: string };
type PipelineOption = { id: string; name: string; color: string; stages: { id: string; name: string }[] };
const emptyContact = { name: '', email: '', phone: '', company: '', notes: '' };
const colors = ['#5B5BD6', '#F26B4A', '#2F9C75', '#D99A2B', '#A455C2'];

type ImportContact = { name: string; email: string; phone: string; company: string; notes: string };
const headerAliases: Record<keyof ImportContact, string[]> = { name: ['nome', 'name', 'nome completo', 'full name'], email: ['email', 'e-mail'], phone: ['telefone', 'phone', 'celular', 'whatsapp'], company: ['empresa', 'company'], notes: ['observacoes', 'observações', 'notes', 'mensagem'] };
function readCsvLine(line: string, separator: string) { const cells: string[] = []; let current = ''; let quoted = false; for (let index = 0; index < line.length; index++) { const char = line[index]; if (char === '"' && line[index + 1] === '"' && quoted) { current += '"'; index++; } else if (char === '"') quoted = !quoted; else if (char === separator && !quoted) { cells.push(current.trim()); current = ''; } else current += char; } cells.push(current.trim()); return cells; }
function parseCsv(text: string): ImportContact[] { const lines = text.replace(/^\uFEFF/, '').split(/\r?\n/).filter((line) => line.trim()); if (lines.length < 2) return []; const separator = (lines[0].match(/;/g)?.length ?? 0) > (lines[0].match(/,/g)?.length ?? 0) ? ';' : ','; const headers = readCsvLine(lines[0], separator).map((header) => header.toLowerCase().trim()); const indexes = Object.fromEntries(Object.entries(headerAliases).map(([key, aliases]) => [key, headers.findIndex((header) => aliases.includes(header))])) as Record<keyof ImportContact, number>; return lines.slice(1).map((line) => { const cells = readCsvLine(line, separator); return { name: cells[indexes.name] ?? '', email: (cells[indexes.email] ?? '').toLowerCase(), phone: cells[indexes.phone] ?? '', company: cells[indexes.company] ?? '', notes: cells[indexes.notes] ?? '' }; }).filter((contact) => contact.name || contact.email || contact.phone); }
function csvCell(value: string) { return `"${value.replaceAll('"', '""')}"`; }

export default function Home() {
  const [view, setView] = useState<'contacts' | 'automation' | 'pipelines'>('contacts');
  const [pipelineOptions, setPipelineOptions] = useState<PipelineOption[]>([]);
  const [lists, setLists] = useState<ContactList[]>([]);
  const [contacts, setContacts] = useState<Contact[]>([]);
  const [selectedId, setSelectedId] = useState('');
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState('');
  const [listModal, setListModal] = useState(false);
  const [contactModal, setContactModal] = useState(false);
  const [editingContact, setEditingContact] = useState<Contact | null>(null);
  const [listForm, setListForm] = useState({ name: '', segment: '', color: colors[0], pipelineId: '', routingStageId: '' });
  const [contactForm, setContactForm] = useState(emptyContact);
  const [importModal, setImportModal] = useState(false);
  const [importRows, setImportRows] = useState<ImportContact[]>([]);
  const [importFile, setImportFile] = useState('');
  const [importing, setImporting] = useState(false);
  const fileInput = useRef<HTMLInputElement>(null);
  const selected = lists.find((list) => list.id === selectedId) ?? lists[0];

  const loadLists = useCallback(async () => {
    const response = await fetch('/api/lists'); const data = (await response.json()) as ContactList[];
    setLists(data); setSelectedId((current) => current || data[0]?.id || ''); setLoading(false);
  }, []);
  const loadPipelineOptions = useCallback(async () => { const response = await fetch('/api/pipelines'); const data = await response.json() as PipelineOption[]; setPipelineOptions(data); }, []);
  const loadContacts = useCallback(async (listId: string) => {
    if (!listId) return setContacts([]);
    const response = await fetch(`/api/contacts?listId=${encodeURIComponent(listId)}`); setContacts((await response.json()) as Contact[]);
  }, []);
  useEffect(() => { loadLists().catch(() => setLoading(false)); }, [loadLists]);
  useEffect(() => { loadPipelineOptions(); }, [loadPipelineOptions]);
  useEffect(() => { if (selected?.id) loadContacts(selected.id); }, [selected?.id, loadContacts]);
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return term ? contacts.filter((contact) => [contact.name, contact.email, contact.phone, contact.company].some((value) => value.toLowerCase().includes(term))) : contacts; }, [contacts, search]);
  function flash(message: string) { setNotice(message); window.setTimeout(() => setNotice(''), 2800); }

  async function saveList(event: FormEvent) {
    event.preventDefault(); const response = await fetch('/api/lists', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(listForm) });
    if (!response.ok) return flash('Não foi possível criar a lista.');
    const created = (await response.json()) as ContactList; if (listForm.pipelineId) await fetch(`/api/lists/${created.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pipelineId: listForm.pipelineId, routingStageId: listForm.routingStageId || null }) }); setListModal(false); setListForm({ name: '', segment: '', color: colors[(lists.length + 1) % colors.length], pipelineId: '', routingStageId: '' }); await loadLists(); setSelectedId(created.id); flash('Lista criada com direcionamento configurado.');
  }
  async function renameList() {
    if (!selected) return; const name = window.prompt('Novo nome da lista', selected.name)?.trim(); if (!name) return;
    await fetch(`/api/lists/${selected.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) }); await loadLists(); flash('Lista atualizada.');
  }
  async function deleteList() {
    if (!selected || !window.confirm(`Excluir “${selected.name}” e todos os seus contatos?`)) return;
    await fetch(`/api/lists/${selected.id}`, { method: 'DELETE' }); setSelectedId(''); await loadLists(); flash('Lista excluída.');
  }
  function openContact(contact?: Contact) { setEditingContact(contact ?? null); setContactForm(contact ? { name: contact.name, email: contact.email, phone: contact.phone, company: contact.company, notes: contact.notes } : emptyContact); setContactModal(true); }
  async function saveContact(event: FormEvent) {
    event.preventDefault(); if (!selected) return;
    const response = await fetch(editingContact ? `/api/contacts/${editingContact.id}` : '/api/contacts', { method: editingContact ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...contactForm, listId: selected.id }) });
    if (!response.ok) return flash('Confira os dados e tente novamente.');
    setContactModal(false); await Promise.all([loadContacts(selected.id), loadLists()]); flash(editingContact ? 'Contato atualizado.' : 'Contato adicionado.');
  }
  async function deleteContact(contact: Contact) { if (!window.confirm(`Excluir o contato ${contact.name || contact.email}?`)) return; await fetch(`/api/contacts/${contact.id}`, { method: 'DELETE' }); await Promise.all([loadContacts(contact.listId), loadLists()]); flash('Contato excluído.'); }
  async function chooseCsv(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const rows = parseCsv(await file.text()); setImportFile(file.name); setImportRows(rows); if (!rows.length) flash('O CSV precisa ter cabeçalho e ao menos um contato válido.'); }
  async function importContacts() { if (!selected || !importRows.length) return; setImporting(true); const response = await fetch('/api/contacts/bulk', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ listId: selected.id, contacts: importRows }) }); const result = await response.json() as { created?: number; duplicates?: number; error?: string }; setImporting(false); if (!response.ok) return flash(result.error || 'Não foi possível importar o arquivo.'); setImportModal(false); setImportRows([]); setImportFile(''); await Promise.all([loadContacts(selected.id), loadLists()]); flash(`${result.created ?? 0} contatos importados${result.duplicates ? ` · ${result.duplicates} duplicados ignorados` : ''}.`); }
  function exportContacts() { if (!selected || !contacts.length) return flash('Esta lista ainda não tem contatos para baixar.'); const header = ['Nome', 'E-mail', 'Telefone', 'Empresa', 'Observações', 'Origem', 'Data e hora de entrada']; const rows = contacts.map((contact) => [contact.name, contact.email, contact.phone, contact.company, contact.notes, contact.source === 'webhook' ? 'Great Pages' : contact.source === 'import' ? 'Importação' : 'Manual', new Date(contact.createdAt).toLocaleString('pt-BR')]); const csv = `\uFEFF${[header, ...rows].map((row) => row.map(csvCell).join(';')).join('\r\n')}`; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); link.download = `${selected.name.toLowerCase().replace(/[^a-z0-9]+/gi, '-')}-contatos.csv`; link.click(); URL.revokeObjectURL(link.href); flash('Arquivo CSV baixado.'); }
  const webhookUrl = selected ? `${typeof window === 'undefined' ? '' : window.location.origin}/api/webhooks/${selected.webhookToken}` : '';

  const sideNav = <div className="main-nav"><button className={view === 'contacts' ? 'active' : ''} onClick={() => setView('contacts')}>☷ <span>Contatos</span></button><button className={view === 'automation' ? 'active' : ''} onClick={() => setView('automation')}>⚡ <span>Automação</span></button><button className={view === 'pipelines' ? 'active' : ''} onClick={() => setView('pipelines')}>▥ <span>Funis de vendas</span></button></div>;
  if (view === 'pipelines') return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">C</span><div><strong>Capta</strong><small>CRM de contatos</small></div></div>{sideNav}<div className="sidebar-foot"><span className="status-dot" /> Integrações preservadas</div></aside><section className="workspace"><header className="topbar"><div><p>PIPELINES</p><h1>Funis de vendas</h1></div></header><PipelineBoard lists={lists} reloadLists={loadLists} flash={flash} /></section>{notice && <div className="toast" role="status">✓ {notice}</div>}</main>;
  if (view === 'automation') return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">C</span><div><strong>Capta</strong><small>CRM de contatos</small></div></div>{sideNav}<div className="sidebar-foot"><span className="status-dot" /> Webhooks ativos</div></aside><section className="workspace"><header className="topbar"><div><p>AUTOMAÇÃO</p><h1>Direcionamentos</h1></div><div className="top-actions"><button className="primary" onClick={() => setView('pipelines')}>Gerenciar funis</button></div></header><AutomationPanel lists={lists} reloadLists={loadLists} flash={flash} openPipelines={() => setView('pipelines')} /></section>{notice && <div className="toast" role="status">✓ {notice}</div>}</main>;

  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">C</span><div><strong>Capta</strong><small>CRM de contatos</small></div></div>{sideNav}<div className="sidebar-foot"><span className="status-dot" /> Integração ativa</div></aside>
    <section className="workspace"><header className="topbar"><div><p>LISTA DE CONTATOS</p><h1>{selected?.name ?? 'Seus contatos'}</h1></div><select className="mobile-list-switch" value={selected?.id || ''} onChange={(event) => setSelectedId(event.target.value)}>{lists.map((list) => <option value={list.id} key={list.id}>{list.name}</option>)}</select><div className="top-actions"><button className="secondary" onClick={() => setView('automation')}>⚡ Automação</button><button className="secondary webhook-copy-top" onClick={() => selected && navigator.clipboard.writeText(webhookUrl).then(() => flash('URL do webhook copiada.'))}>↗ URL</button><button className="primary" onClick={() => openContact()} disabled={!selected}>+ Adicionar contato</button></div></header>
      <section className="contact-list-strip"><div><span className="eyebrow">LISTAS DE CONTATOS</span><strong>Suas captações</strong></div><nav>{lists.map((list) => <button key={list.id} className={list.id === selected?.id ? 'active' : ''} onClick={() => setSelectedId(list.id)}><i style={{ background: list.color }} /><span>{list.name}<small>{list.contactCount} contatos</small></span></button>)}<button className="create-list-chip" onClick={() => setListModal(true)}>+ Nova lista</button></nav></section>
      <div className="content">{loading ? <div className="empty"><h2>Carregando seu CRM…</h2></div> : !selected ? <div className="empty"><span>↗</span><h2>Crie sua primeira lista</h2><p>Separe os leads por campanha, produto ou segmento.</p><button className="primary" onClick={() => setListModal(true)}>Criar lista</button></div> : <><div className="summary-row"><div><strong>{selected.contactCount}</strong><span>contatos nesta lista</span></div><div><strong>{contacts.filter((c) => c.source === 'webhook').length}</strong><span>recebidos via webhook</span></div><div className="summary-accent"><strong>{selected.segment || 'Sem segmento'}</strong><span>segmento</span></div></div>
        <section className="integration-card"><div className="integration-icon">↗</div><div className="integration-copy"><div><span className="eyebrow">INTEGRAÇÃO GREAT PAGES</span><h2>Webhook desta lista</h2><p>Use esta URL no Great Pages. Cada novo lead entrará automaticamente em <strong>{selected.name}</strong>.</p></div><div className="webhook-box"><code>{webhookUrl}</code><button onClick={() => navigator.clipboard.writeText(webhookUrl).then(() => flash('URL copiada.'))}>Copiar</button></div></div><span className="live-badge">● Ativo</span></section>
        <div className="toolbar"><label className="search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por nome, e-mail, telefone ou empresa" /></label><div><button className="secondary small" onClick={() => setImportModal(true)}>↑ Importar CSV</button><button className="secondary small" onClick={exportContacts}>↓ Baixar contatos</button><button className="secondary small" onClick={renameList}>Editar lista</button><button className="danger small" onClick={deleteList}>Excluir lista</button></div></div>
        <section className="table-card"><table><thead><tr><th>CONTATO</th><th>TELEFONE</th><th>EMPRESA</th><th>ORIGEM</th><th>ENTRADA</th><th aria-label="Ações" /></tr></thead><tbody>{filtered.map((contact) => <tr key={contact.id}><td><div className="person"><span>{(contact.name || contact.email || '?').slice(0, 1).toUpperCase()}</span><div><strong>{contact.name || 'Sem nome'}</strong><small>{contact.email || 'Sem e-mail'}</small></div></div></td><td>{contact.phone || '—'}</td><td>{contact.company || '—'}</td><td><span className={contact.source === 'webhook' ? 'source webhook' : 'source manual'}>{contact.source === 'webhook' ? 'Great Pages' : contact.source === 'import' ? 'Importado' : 'Manual'}</span></td><td><time className="entry-time">{new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' }).format(new Date(contact.createdAt))}<small>{new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit' }).format(new Date(contact.createdAt))}</small></time></td><td><div className="row-actions"><button onClick={() => openContact(contact)}>Editar</button><button onClick={() => deleteContact(contact)}>Excluir</button></div></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="table-empty"><h3>Nenhum contato encontrado</h3><p>Adicione manualmente ou envie um lead pelo webhook desta lista.</p></div>}</section></>}</div>
    </section>
    {notice && <div className="toast" role="status">✓ {notice}</div>}
    {listModal && <div className="modal-backdrop" onMouseDown={() => setListModal(false)}><form className="modal" onSubmit={saveList} onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">NOVA CAPTAÇÃO</span><h2>Criar lista</h2></div><button type="button" onClick={() => setListModal(false)}>×</button></div><label>Nome da lista<input required autoFocus value={listForm.name} onChange={(e) => setListForm({ ...listForm, name: e.target.value })} placeholder="Ex.: Leads do e-book" /></label><label>Segmento<input value={listForm.segment} onChange={(e) => setListForm({ ...listForm, segment: e.target.value })} placeholder="Ex.: Imobiliário" /></label><div className="form-grid"><label>Funil de destino<select className="form-select" value={listForm.pipelineId} onChange={(e) => { const pipelineId = e.target.value; setListForm({ ...listForm, pipelineId, routingStageId: pipelineOptions.find((pipeline) => pipeline.id === pipelineId)?.stages[0]?.id || '' }); }}><option value="">Não direcionar agora</option>{pipelineOptions.map((pipeline) => <option value={pipeline.id} key={pipeline.id}>{pipeline.name}</option>)}</select></label><label>Etapa de entrada<select className="form-select" value={listForm.routingStageId} disabled={!listForm.pipelineId} onChange={(e) => setListForm({ ...listForm, routingStageId: e.target.value })}><option value="">Primeira etapa</option>{pipelineOptions.find((pipeline) => pipeline.id === listForm.pipelineId)?.stages.map((stage) => <option value={stage.id} key={stage.id}>{stage.name}</option>)}</select></label></div><small className="field-help">Você poderá alterar depois na aba Automação.</small><fieldset><legend>Cor da lista</legend><div className="color-picker">{colors.map((color) => <button type="button" key={color} aria-label={`Cor ${color}`} className={listForm.color === color ? 'selected' : ''} style={{ background: color }} onClick={() => setListForm({ ...listForm, color })} />)}</div></fieldset><div className="modal-actions"><button type="button" className="secondary" onClick={() => setListModal(false)}>Cancelar</button><button className="primary">Criar lista</button></div></form></div>}
    {contactModal && <div className="modal-backdrop" onMouseDown={() => setContactModal(false)}><form className="modal" onSubmit={saveContact} onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">{editingContact ? 'EDITAR CADASTRO' : 'NOVO CADASTRO'}</span><h2>{editingContact ? 'Editar contato' : 'Adicionar contato'}</h2></div><button type="button" onClick={() => setContactModal(false)}>×</button></div><div className="form-grid"><label>Nome<input autoFocus value={contactForm.name} onChange={(e) => setContactForm({ ...contactForm, name: e.target.value })} placeholder="Nome completo" /></label><label>E-mail<input type="email" value={contactForm.email} onChange={(e) => setContactForm({ ...contactForm, email: e.target.value })} placeholder="nome@empresa.com" /></label><label>Telefone<input value={contactForm.phone} onChange={(e) => setContactForm({ ...contactForm, phone: e.target.value })} placeholder="(00) 00000-0000" /></label><label>Empresa<input value={contactForm.company} onChange={(e) => setContactForm({ ...contactForm, company: e.target.value })} placeholder="Empresa" /></label></div><label>Observações<textarea rows={3} value={contactForm.notes} onChange={(e) => setContactForm({ ...contactForm, notes: e.target.value })} placeholder="Informações úteis sobre o lead" /></label><p className="form-hint">Preencha ao menos nome, e-mail ou telefone.</p><div className="modal-actions"><button type="button" className="secondary" onClick={() => setContactModal(false)}>Cancelar</button><button className="primary">Salvar contato</button></div></form></div>}
    {importModal && <div className="modal-backdrop" onMouseDown={() => setImportModal(false)}><section className="modal import-modal" onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">IMPORTAÇÃO EM MASSA</span><h2>Adicionar vários contatos</h2></div><button type="button" onClick={() => setImportModal(false)}>×</button></div><button className="upload-zone" type="button" onClick={() => fileInput.current?.click()}><span>↑</span><strong>{importFile || 'Selecionar arquivo CSV'}</strong><small>Colunas aceitas: nome, email, telefone, empresa e observações</small></button><input ref={fileInput} className="file-input" type="file" accept=".csv,text/csv" onChange={chooseCsv} />{importRows.length > 0 && <div className="import-preview"><div><strong>{importRows.length}</strong><span>contatos prontos para importar</span></div><table><thead><tr><th>NOME</th><th>E-MAIL</th><th>TELEFONE</th></tr></thead><tbody>{importRows.slice(0, 4).map((contact, index) => <tr key={`${contact.email}-${index}`}><td>{contact.name || '—'}</td><td>{contact.email || '—'}</td><td>{contact.phone || '—'}</td></tr>)}</tbody></table>{importRows.length > 4 && <small>e mais {importRows.length - 4} contatos…</small>}</div>}<a className="template-link" href={'data:text/csv;charset=utf-8,' + encodeURIComponent('Nome;E-mail;Telefone;Empresa;Observações\nMaria Silva;maria@empresa.com;11999999999;Empresa Exemplo;Lead do evento')} download="modelo-contatos-capta.csv">↓ Baixar modelo de CSV</a><div className="modal-actions"><button type="button" className="secondary" onClick={() => setImportModal(false)}>Cancelar</button><button type="button" className="primary" disabled={!importRows.length || importing} onClick={importContacts}>{importing ? 'Importando…' : `Importar ${importRows.length || ''} contatos`}</button></div></section></div>}
  </main>;
}
