'use client';
import { useEffect, useMemo, useState } from 'react';
type Contact = { id: string; pipelineId: string | null; negotiationValueCents: number; saleCompleted: boolean; source: string; createdAt: string; assignedSeller: { id: string; name: string } | null; tasks: { completed: boolean }[] };
type Pipeline = { id: string; name: string; color: string };
type SellerResult = { id: string; name: string; leads: number; conversion: number; sales: number; revenue: number; ticket: number; tasks: number };
type FunnelResult = Pipeline & { leads: number; sales: number; conversion: number; revenue: number };
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
export default function DashboardPanel() {
  const [allContacts, setAllContacts] = useState<Contact[]>([]); const [pipelines, setPipelines] = useState<Pipeline[]>([]); const [period, setPeriod] = useState('all'); const [loading, setLoading] = useState(true);
  const [sellerSort, setSellerSort] = useState<keyof Pick<SellerResult, 'leads' | 'conversion' | 'sales' | 'revenue' | 'ticket' | 'tasks'>>('revenue'); const [sellerDirection, setSellerDirection] = useState<'desc' | 'asc'>('desc'); const [funnelDirection, setFunnelDirection] = useState<'desc' | 'asc'>('desc');
  useEffect(() => { fetch('/api/dashboard').then((response) => response.json() as Promise<{ contacts?: Contact[]; pipelines?: Pipeline[] }>).then((data) => { setAllContacts(data.contacts || []); setPipelines(data.pipelines || []); setLoading(false); }); }, []);
  const months = useMemo(() => [...new Set(allContacts.map((contact) => contact.createdAt.slice(0, 7)))].sort().reverse(), [allContacts]);
  const contacts = useMemo(() => period === 'all' ? allContacts : allContacts.filter((contact) => contact.createdAt.slice(0, 7) === period), [allContacts, period]);
  const sold = contacts.filter((contact) => contact.saleCompleted); const potential = contacts.reduce((sum, contact) => sum + contact.negotiationValueCents, 0); const revenue = sold.reduce((sum, contact) => sum + contact.negotiationValueCents, 0);
  const sellerResults = useMemo(() => { const map = new Map<string, { id: string; name: string; contacts: Contact[] }>(); contacts.forEach((contact) => { const id = contact.assignedSeller?.id || 'unassigned'; const current = map.get(id) || { id, name: contact.assignedSeller?.name || 'Não atribuídos', contacts: [] }; current.contacts.push(contact); map.set(id, current); }); const results: SellerResult[] = [...map.values()].map((seller) => { const sales = seller.contacts.filter((contact) => contact.saleCompleted); const sellerRevenue = sales.reduce((sum, contact) => sum + contact.negotiationValueCents, 0); return { id: seller.id, name: seller.name, leads: seller.contacts.length, conversion: seller.contacts.length ? Math.round(sales.length / seller.contacts.length * 100) : 0, sales: sales.length, revenue: sellerRevenue, ticket: sales.length ? sellerRevenue / sales.length : 0, tasks: seller.contacts.reduce((sum, contact) => sum + contact.tasks.filter((task) => !task.completed).length, 0) }; }); return results.sort((a, b) => (a[sellerSort] - b[sellerSort]) * (sellerDirection === 'desc' ? -1 : 1)); }, [contacts, sellerSort, sellerDirection]);
  const ranking = useMemo<FunnelResult[]>(() => pipelines.map((pipeline) => { const leads = contacts.filter((contact) => contact.pipelineId === pipeline.id); const sales = leads.filter((contact) => contact.saleCompleted); return { ...pipeline, leads: leads.length, sales: sales.length, conversion: leads.length ? Math.round(sales.length / leads.length * 100) : 0, revenue: sales.reduce((sum, contact) => sum + contact.negotiationValueCents, 0) }; }).filter((pipeline) => pipeline.leads > 0), [pipelines, contacts]);
  const best = [...ranking].sort((a, b) => b.conversion - a.conversion || b.revenue - a.revenue).slice(0, 3); const worst = [...ranking].sort((a, b) => a.conversion - b.conversion || a.revenue - b.revenue).slice(0, 3); const order = <T,>(items: T[]) => funnelDirection === 'desc' ? items : [...items].reverse();
  if (loading) return <div className="dashboard-loading">Carregando indicadores…</div>;
  const Ranking = ({ title, items, tone }: { title: string; items: FunnelResult[]; tone: string }) => <section className={`dashboard-card ranking-card ${tone}`}><header><span className="eyebrow">DESEMPENHO DOS FUNIS</span><h2>{title}</h2></header>{order(items).map((pipeline, index) => <article key={pipeline.id}><b>{index + 1}</b><div><strong>{pipeline.name}</strong><small>{pipeline.leads} leads · {pipeline.sales} vendas</small></div><span>{pipeline.conversion}%</span><em>{money.format(pipeline.revenue / 100)}</em></article>)}{!items.length && <p className="dashboard-empty">Sem dados neste período.</p>}</section>;
  return <div className="dashboard-screen">
    <section className="dashboard-filter"><div><span className="eyebrow">PERÍODO DOS INDICADORES</span><strong>{period === 'all' ? 'Todo o histórico do CRM' : new Date(`${period}-01T12:00:00`).toLocaleDateString('pt-BR', { month: 'long', year: 'numeric' })}</strong></div><select value={period} onChange={(event) => setPeriod(event.target.value)}><option value="all">Resultado total</option>{months.map((month) => <option key={month} value={month}>{new Date(`${month}-01T12:00:00`).toLocaleDateString('pt-BR', { month: 'long', year: 'numeric' })}</option>)}</select></section>
    <section className="dashboard-kpis"><article><span>Todos os leads</span><strong>{contacts.length}</strong><small>{contacts.filter((contact) => !contact.pipelineId).length} ainda sem funil</small></article><article><span>Conversão total</span><strong>{contacts.length ? Math.round(sold.length / contacts.length * 100) : 0}%</strong><small>{sold.length} vendas concluídas</small></article><article><span>Vendas realizadas</span><strong>{money.format(revenue / 100)}</strong><small>Faturamento confirmado</small></article><article><span>Ticket médio</span><strong>{money.format(sold.length ? revenue / sold.length / 100 : 0)}</strong><small>Por venda concluída</small></article><article><span>Potencial total</span><strong>{money.format(potential / 100)}</strong><small>{money.format((potential - revenue) / 100)} em aberto</small></article></section>
    <section className="dashboard-card seller-performance"><header className="result-header"><div><span className="eyebrow">EQUIPE COMERCIAL</span><h2>Resultados por vendedor</h2></div><div className="sort-controls"><select value={sellerSort} onChange={(event) => setSellerSort(event.target.value as typeof sellerSort)}><option value="revenue">Faturamento</option><option value="conversion">Conversão</option><option value="sales">Vendas</option><option value="ticket">Ticket médio</option><option value="leads">Leads</option><option value="tasks">Tarefas pendentes</option></select><select value={sellerDirection} onChange={(event) => setSellerDirection(event.target.value as 'desc' | 'asc')}><option value="desc">Maior para menor</option><option value="asc">Menor para maior</option></select></div></header><div className="seller-table wide"><div className="seller-table-head"><span>Vendedor</span><span>Leads</span><span>Conversão</span><span>Vendas</span><span>Ticket médio</span><span>Tarefas pendentes</span><span>Faturamento</span></div>{sellerResults.map((seller) => <div className="seller-row" key={seller.id}><strong>{seller.name}</strong><span>{seller.leads}</span><span>{seller.conversion}%</span><span>{seller.sales}</span><span>{money.format(seller.ticket / 100)}</span><span className="pending-task-count">{seller.tasks}</span><b>{money.format(seller.revenue / 100)}</b></div>)}</div></section>
    <div className="dashboard-grid dashboard-grid-single"><section className="dashboard-card source-card"><header><span className="eyebrow">ORIGEM DOS LEADS</span><h2>Captação completa</h2></header>{[['GreatPages', contacts.filter((contact) => contact.source === 'webhook').length], ['Importação', contacts.filter((contact) => contact.source === 'import').length], ['Cadastro manual', contacts.filter((contact) => contact.source === 'manual').length]].map(([label, value]) => <div className="source-row" key={label}><span>{label}</span><strong>{value}</strong><i><em style={{ width: `${contacts.length ? Number(value) / contacts.length * 100 : 0}%` }} /></i></div>)}</section></div>
    <div className="ranking-sort"><span>Ordenar resultados dos funis</span><select value={funnelDirection} onChange={(event) => setFunnelDirection(event.target.value as 'desc' | 'asc')}><option value="desc">Maior para menor</option><option value="asc">Menor para maior</option></select></div><div className="ranking-grid"><Ranking title="3 melhores funis" items={best} tone="best" /><Ranking title="3 funis com mais atenção" items={worst} tone="worst" /></div>
  </div>;
}
