'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';

type Task = { id: string; title: string; dueDate: string | null; completed: boolean };
type Card = { id: string; stageId: string; name: string; email: string; phone: string; company: string; notes: string; source: string; tasks: Task[] };
type Stage = { id: string; name: string; color: string; position: number; cards: Card[] };
type Pipeline = { id: string; name: string; color: string; stages: Stage[]; lists: { id: string; name: string; pipelineId: string | null }[] };
type ContactList = { id: string; name: string; pipelineId: string | null };

export default function PipelineBoard({ lists, reloadLists, flash }: { lists: ContactList[]; reloadLists: () => Promise<void>; flash: (message: string) => void }) {
  const [pipelines, setPipelines] = useState<Pipeline[]>([]); const [selectedId, setSelectedId] = useState(''); const [loading, setLoading] = useState(true); const [card, setCard] = useState<Card | null>(null); const [taskTitle, setTaskTitle] = useState(''); const [taskDate, setTaskDate] = useState('');
  const selected = pipelines.find((pipeline) => pipeline.id === selectedId) ?? pipelines[0];
  const load = useCallback(async () => { const response = await fetch('/api/pipelines'); const data = await response.json() as Pipeline[]; setPipelines(data); setSelectedId((current) => data.some((pipeline) => pipeline.id === current) ? current : data[0]?.id || ''); setLoading(false); }, []);
  useEffect(() => { load(); }, [load]);

  async function createPipeline() { const name = window.prompt('Nome do novo funil')?.trim(); if (!name) return; await fetch('/api/pipelines', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) }); await load(); flash('Funil criado com etapas iniciais.'); }
  async function editPipeline() { if (!selected) return; const name = window.prompt('Nome do funil', selected.name)?.trim(); if (!name) return; await fetch(`/api/pipelines/${selected.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) }); await load(); flash('Funil atualizado.'); }
  async function deletePipeline() { if (!selected || !window.confirm(`Excluir o funil “${selected.name}”? Os contatos permanecerão nas listas.`)) return; await fetch(`/api/pipelines/${selected.id}`, { method: 'DELETE' }); await Promise.all([load(), reloadLists()]); flash('Funil excluído.'); }
  async function addStage() { if (!selected) return; const name = window.prompt('Nome da nova etapa')?.trim(); if (!name) return; await fetch(`/api/pipelines/${selected.id}/stages`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) }); await load(); flash('Etapa adicionada.'); }
  async function editStage(stage: Stage) { const name = window.prompt('Nome da etapa', stage.name)?.trim(); if (!name) return; await fetch(`/api/stages/${stage.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) }); await load(); }
  async function deleteStage(stage: Stage) { if (!window.confirm(`Excluir a etapa “${stage.name}”? Os cartões ficarão sem etapa.`)) return; await fetch(`/api/stages/${stage.id}`, { method: 'DELETE' }); await load(); flash('Etapa excluída.'); }
  async function moveCard(contactId: string, stageId: string) { setPipelines((current) => current.map((pipeline) => ({ ...pipeline, stages: pipeline.stages.map((stage) => ({ ...stage, cards: stage.cards.filter((item) => item.id !== contactId).concat(stage.id === stageId ? pipeline.stages.flatMap((item) => item.cards).filter((item) => item.id === contactId).map((item) => ({ ...item, stageId })) : []) })) }))); await fetch(`/api/contacts/${contactId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ stageId }) }); await load(); }
  async function assignList(listId: string, pipelineId: string | null) { await fetch(`/api/lists/${listId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pipelineId }) }); await Promise.all([load(), reloadLists()]); flash('Direcionamento da lista atualizado.'); }
  async function saveCard(event: FormEvent) { event.preventDefault(); if (!card) return; await fetch(`/api/contacts/${card.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: card.name, email: card.email, phone: card.phone, company: card.company, notes: card.notes }) }); setCard(null); await load(); flash('Cartão atualizado.'); }
  async function addTask(event: FormEvent) { event.preventDefault(); if (!card || !taskTitle.trim()) return; await fetch('/api/tasks', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contactId: card.id, title: taskTitle, dueDate: taskDate }) }); setTaskTitle(''); setTaskDate(''); await load(); const response = await fetch('/api/pipelines'); const data = await response.json() as Pipeline[]; const updated = data.flatMap((pipeline) => pipeline.stages).flatMap((stage) => stage.cards).find((item) => item.id === card.id); if (updated) setCard(updated); }
  async function toggleTask(task: Task) { await fetch(`/api/tasks/${task.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ completed: !task.completed }) }); setCard((current) => current ? { ...current, tasks: current.tasks.map((item) => item.id === task.id ? { ...item, completed: !item.completed } : item) } : null); load(); }
  async function deleteTask(taskId: string) { await fetch(`/api/tasks/${taskId}`, { method: 'DELETE' }); setCard((current) => current ? { ...current, tasks: current.tasks.filter((task) => task.id !== taskId) } : null); load(); }

  if (loading) return <div className="empty"><h2>Carregando funis…</h2></div>;
  return <div className="pipeline-screen">
    <div className="pipeline-toolbar"><div className="pipeline-tabs">{pipelines.map((pipeline) => <button key={pipeline.id} className={pipeline.id === selected?.id ? 'active' : ''} onClick={() => setSelectedId(pipeline.id)}><span style={{ background: pipeline.color }} />{pipeline.name}</button>)}<button className="add-pipeline" onClick={createPipeline}>+ Novo funil</button></div>{selected && <div className="pipeline-actions"><button className="secondary small" onClick={editPipeline}>Editar funil</button><button className="secondary small" onClick={addStage}>+ Etapa</button><button className="danger small" onClick={deletePipeline}>Excluir funil</button></div>}</div>
    {!selected ? <div className="empty"><span>↗</span><h2>Crie seu primeiro funil</h2><p>Organize o acompanhamento dos leads em etapas visuais.</p><button className="primary" onClick={createPipeline}>Criar funil de vendas</button></div> : <>
      <section className="routing-panel"><div><span className="eyebrow">DIRECIONAMENTO AUTOMÁTICO</span><h2>Listas conectadas a este funil</h2><p>Todo novo contato entra automaticamente na primeira etapa.</p></div><div className="routing-lists">{lists.map((list) => <label key={list.id}><span>{list.name}</span><select value={list.pipelineId || ''} onChange={(event) => assignList(list.id, event.target.value || null)}><option value="">Sem funil</option>{pipelines.map((pipeline) => <option value={pipeline.id} key={pipeline.id}>{pipeline.name}</option>)}</select></label>)}</div></section>
      <section className="kanban-board">{selected.stages.map((stage) => <div className="kanban-column" key={stage.id} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const id = event.dataTransfer.getData('text/contact-id'); if (id) moveCard(id, stage.id); }}><header><div><span style={{ background: stage.color }} /><strong>{stage.name}</strong><small>{stage.cards.length}</small></div><div><button onClick={() => editStage(stage)} aria-label={`Editar ${stage.name}`}>✎</button><button onClick={() => deleteStage(stage)} aria-label={`Excluir ${stage.name}`}>×</button></div></header><div className="kanban-cards">{stage.cards.map((item) => <article className="kanban-card" key={item.id} draggable onDragStart={(event) => { event.dataTransfer.setData('text/contact-id', item.id); event.dataTransfer.effectAllowed = 'move'; }} onClick={() => setCard(item)}><div className="card-top"><span>{(item.name || item.email || '?').slice(0, 1).toUpperCase()}</span><small>{item.source === 'webhook' ? 'Great Pages' : item.source === 'import' ? 'Importado' : 'Manual'}</small></div><h3>{item.name || 'Sem nome'}</h3><p>{item.company || item.email || item.phone || 'Sem detalhes'}</p><footer><span>☑ {item.tasks.filter((task) => !task.completed).length} tarefas</span><button onClick={(event) => { event.stopPropagation(); setCard(item); }}>Editar</button></footer></article>)}{!stage.cards.length && <div className="column-empty">Arraste cartões para cá</div>}</div></div>)}<button className="add-column" onClick={addStage}>+ Nova etapa</button></section>
    </>}
    {card && <div className="modal-backdrop" onMouseDown={() => setCard(null)}><section className="modal card-modal" onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">CARTÃO DO LEAD</span><h2>{card.name || 'Editar cartão'}</h2></div><button onClick={() => setCard(null)}>×</button></div><form onSubmit={saveCard}><div className="form-grid"><label>Nome<input value={card.name} onChange={(event) => setCard({ ...card, name: event.target.value })} /></label><label>E-mail<input type="email" value={card.email} onChange={(event) => setCard({ ...card, email: event.target.value })} /></label><label>Telefone<input value={card.phone} onChange={(event) => setCard({ ...card, phone: event.target.value })} /></label><label>Empresa<input value={card.company} onChange={(event) => setCard({ ...card, company: event.target.value })} /></label></div><label>Observações<textarea rows={3} value={card.notes} onChange={(event) => setCard({ ...card, notes: event.target.value })} /></label><button className="primary save-card">Salvar alterações</button></form><section className="tasks-panel"><div className="tasks-title"><span className="eyebrow">TAREFAS</span><strong>{card.tasks.filter((task) => !task.completed).length} pendentes</strong></div><div className="task-list">{card.tasks.map((task) => <div className={task.completed ? 'task completed' : 'task'} key={task.id}><button onClick={() => toggleTask(task)}>{task.completed ? '✓' : ''}</button><span>{task.title}<small>{task.dueDate ? new Date(task.dueDate).toLocaleDateString('pt-BR') : 'Sem prazo'}</small></span><button onClick={() => deleteTask(task.id)}>×</button></div>)}</div><form className="add-task" onSubmit={addTask}><input value={taskTitle} onChange={(event) => setTaskTitle(event.target.value)} placeholder="Nova tarefa…" /><input type="date" value={taskDate} onChange={(event) => setTaskDate(event.target.value)} /><button className="secondary">Adicionar</button></form></section></section></div>}
  </div>;
}
