'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';

type Task = { id: string; title: string; dueDate: string | null; completed: boolean };
type Card = { id: string; stageId: string; assignedUserId: string | null; assignedSeller: { id: string; name: string; email: string } | null; name: string; email: string; phone: string; company: string; notes: string; source: string; tasks: Task[] };
type Stage = { id: string; name: string; color: string; position: number; cards: Card[] };
type Pipeline = { id: string; name: string; color: string; stages: Stage[]; lists: { id: string; name: string; pipelineId: string | null }[] };
type ContactList = { id: string; name: string; pipelineId: string | null };

export default function PipelineBoard({ lists, reloadLists, flash }: { lists: ContactList[]; reloadLists: () => Promise<void>; flash: (message: string) => void }) {
  const [pipelines, setPipelines] = useState<Pipeline[]>([]); const [selectedId, setSelectedId] = useState(''); const [loading, setLoading] = useState(true); const [card, setCard] = useState<Card | null>(null); const [taskTitle, setTaskTitle] = useState(''); const [taskDate, setTaskDate] = useState('');
  const [cardSize, setCardSize] = useState<'compact' | 'comfortable' | 'large'>('comfortable');
  const [stageEditor, setStageEditor] = useState<{ id?: string; name: string; color: string } | null>(null);
  const [sellers, setSellers] = useState<{ id: string; name: string; email: string }[]>([]); const [sellerFilter, setSellerFilter] = useState('all'); const [currentRole, setCurrentRole] = useState('');
  const selected = pipelines.find((pipeline) => pipeline.id === selectedId) ?? pipelines[0];
  const load = useCallback(async () => { const response = await fetch('/api/pipelines'); const data = await response.json() as Pipeline[]; setPipelines(data); setSelectedId((current) => data.some((pipeline) => pipeline.id === current) ? current : data[0]?.id || ''); setLoading(false); }, []);
  useEffect(() => { load(); Promise.all([fetch('/api/team').then((response) => response.json()), fetch('/api/team/me').then((response) => response.json())]).then(([team, me]) => { const available = (team as { id: string; name: string; email: string; role: string; active: boolean }[]).filter((member) => member.role === 'sales' && member.active); setSellers(available); setCurrentRole(me.role || ''); if (me.role === 'sales') setSellerFilter(me.memberId); }); }, [load]);
  useEffect(() => { const saved = window.localStorage.getItem('capta-card-size'); if (saved === 'compact' || saved === 'comfortable' || saved === 'large') setCardSize(saved); }, []);
  function changeCardSize(size: 'compact' | 'comfortable' | 'large') { setCardSize(size); window.localStorage.setItem('capta-card-size', size); }
  function cardsFor(stage: Stage) { return sellerFilter === 'all' ? stage.cards : sellerFilter === 'unassigned' ? stage.cards.filter((item) => !item.assignedUserId) : stage.cards.filter((item) => item.assignedUserId === sellerFilter); }

  async function createPipeline() { const name = window.prompt('Nome do novo funil')?.trim(); if (!name) return; await fetch('/api/pipelines', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) }); await load(); flash('Funil criado com etapas iniciais.'); }
  async function editPipeline() { if (!selected) return; const name = window.prompt('Nome do funil', selected.name)?.trim(); if (!name) return; await fetch(`/api/pipelines/${selected.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) }); await load(); flash('Funil atualizado.'); }
  async function deletePipeline() { if (!selected || !window.confirm(`Excluir o funil “${selected.name}”? Os contatos permanecerão nas listas.`)) return; await fetch(`/api/pipelines/${selected.id}`, { method: 'DELETE' }); await Promise.all([load(), reloadLists()]); flash('Funil excluído.'); }
  function addStage() { if (selected) setStageEditor({ name: '', color: '#7C3AED' }); }
  function editStage(stage: Stage) { setStageEditor({ id: stage.id, name: stage.name, color: stage.color }); }
  async function saveStage(event: FormEvent) { event.preventDefault(); if (!selected || !stageEditor?.name.trim()) return; const url = stageEditor.id ? `/api/stages/${stageEditor.id}` : `/api/pipelines/${selected.id}/stages`; await fetch(url, { method: stageEditor.id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: stageEditor.name, color: stageEditor.color }) }); setStageEditor(null); await load(); flash(stageEditor.id ? 'Etapa atualizada.' : 'Etapa adicionada.'); }
  async function deleteStage(stage: Stage) { if (!window.confirm(`Excluir a etapa “${stage.name}”? Os cartões ficarão sem etapa.`)) return; await fetch(`/api/stages/${stage.id}`, { method: 'DELETE' }); await load(); flash('Etapa excluída.'); }
  async function moveStage(stage: Stage, direction: -1 | 1) { if (!selected) return; const index = selected.stages.findIndex((item) => item.id === stage.id); const other = selected.stages[index + direction]; if (!other) return; await Promise.all([fetch(`/api/stages/${stage.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ position: other.position }) }), fetch(`/api/stages/${other.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ position: stage.position }) })]); await load(); flash('Posição da etapa atualizada.'); }
  async function moveCard(contactId: string, stageId: string) { setPipelines((current) => current.map((pipeline) => ({ ...pipeline, stages: pipeline.stages.map((stage) => ({ ...stage, cards: stage.cards.filter((item) => item.id !== contactId).concat(stage.id === stageId ? pipeline.stages.flatMap((item) => item.cards).filter((item) => item.id === contactId).map((item) => ({ ...item, stageId })) : []) })) }))); await fetch(`/api/contacts/${contactId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ stageId }) }); await load(); }
  async function assignList(listId: string, pipelineId: string | null) { await fetch(`/api/lists/${listId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pipelineId }) }); await Promise.all([load(), reloadLists()]); flash('Direcionamento da lista atualizado.'); }
  async function saveCard(event: FormEvent) { event.preventDefault(); if (!card) return; await fetch(`/api/contacts/${card.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: card.name, email: card.email, phone: card.phone, company: card.company, notes: card.notes }) }); setCard(null); await load(); flash('Cartão atualizado.'); }
  async function addTask(event: FormEvent) { event.preventDefault(); if (!card || !taskTitle.trim()) return; await fetch('/api/tasks', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contactId: card.id, title: taskTitle, dueDate: taskDate }) }); setTaskTitle(''); setTaskDate(''); await load(); const response = await fetch('/api/pipelines'); const data = await response.json() as Pipeline[]; const updated = data.flatMap((pipeline) => pipeline.stages).flatMap((stage) => stage.cards).find((item) => item.id === card.id); if (updated) setCard(updated); }
  async function toggleTask(task: Task) { await fetch(`/api/tasks/${task.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ completed: !task.completed }) }); setCard((current) => current ? { ...current, tasks: current.tasks.map((item) => item.id === task.id ? { ...item, completed: !item.completed } : item) } : null); load(); }
  async function deleteTask(taskId: string) { await fetch(`/api/tasks/${taskId}`, { method: 'DELETE' }); setCard((current) => current ? { ...current, tasks: current.tasks.filter((task) => task.id !== taskId) } : null); load(); }

  if (loading) return <div className="empty"><h2>Carregando funis…</h2></div>;
  return <div className="pipeline-screen" data-card-size={cardSize}>
    <div className="pipeline-toolbar"><div className="pipeline-tabs">{pipelines.map((pipeline) => <button key={pipeline.id} className={pipeline.id === selected?.id ? 'active' : ''} onClick={() => setSelectedId(pipeline.id)}><span style={{ background: pipeline.color }} />{pipeline.name}</button>)}<button className="add-pipeline" onClick={createPipeline}>+ Novo funil</button></div>{selected && <div className="pipeline-actions"><label className="seller-filter"><span>Visualizar vendedor</span><select value={sellerFilter} onChange={(event) => setSellerFilter(event.target.value)}><option value="all">Todos os vendedores</option>{sellers.map((seller) => <option value={seller.id} key={seller.id}>{seller.name}</option>)}{currentRole === 'manager' && <option value="unassigned">Não atribuídos</option>}</select></label><div className="card-size-control" aria-label="Tamanho dos cartões"><span>Cartões</span><button className={cardSize === 'compact' ? 'active' : ''} onClick={() => changeCardSize('compact')} title="Compacto">P</button><button className={cardSize === 'comfortable' ? 'active' : ''} onClick={() => changeCardSize('comfortable')} title="Médio">M</button><button className={cardSize === 'large' ? 'active' : ''} onClick={() => changeCardSize('large')} title="Grande">G</button></div><button className="secondary small" onClick={editPipeline}>Editar funil</button><button className="primary small" onClick={addStage}>+ Nova etapa</button><button className="danger small" onClick={deletePipeline}>Excluir</button></div>}</div>
    {!selected ? <div className="empty"><span>↗</span><h2>Crie seu primeiro funil</h2><p>Organize o acompanhamento dos leads em etapas visuais.</p><button className="primary" onClick={createPipeline}>Criar funil de vendas</button></div> : <>
      <section className="kanban-board">{selected.stages.map((stage, stageIndex) => <div className="kanban-column" key={stage.id} style={{ borderTopColor: stage.color }} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const id = event.dataTransfer.getData('text/contact-id'); if (id) moveCard(id, stage.id); }}><header style={{ background: stage.color }}><div><span /><strong>{stage.name}</strong><small>{cardsFor(stage).length}</small></div><div className="stage-actions"><button disabled={stageIndex === 0} onClick={() => moveStage(stage, -1)} aria-label={`Mover ${stage.name} para trás`}>←</button><button disabled={stageIndex === selected.stages.length - 1} onClick={() => moveStage(stage, 1)} aria-label={`Mover ${stage.name} para frente`}>→</button><button onClick={() => editStage(stage)} aria-label={`Editar ${stage.name}`}>✎</button><button onClick={() => deleteStage(stage)} aria-label={`Excluir ${stage.name}`}>×</button></div></header><div className="kanban-cards">{cardsFor(stage).map((item) => <article className="kanban-card" key={item.id} style={{ borderLeftColor: stage.color }} draggable onDragStart={(event) => { event.dataTransfer.setData('text/contact-id', item.id); event.dataTransfer.effectAllowed = 'move'; }} onClick={() => setCard(item)}><div className="card-top"><span style={{ background: stage.color }}>{(item.name || item.email || '?').slice(0, 1).toUpperCase()}</span><small>{item.source === 'webhook' ? 'Great Pages' : item.source === 'import' ? 'Importado' : 'Manual'}</small></div><h3>{item.name || 'Sem nome'}</h3><p>{item.company || item.email || item.phone || 'Sem detalhes'}</p>{item.assignedSeller && <div className="kanban-seller"><i>{item.assignedSeller.name.slice(0, 1).toUpperCase()}</i><span>{item.assignedSeller.name}</span></div>}<footer><span>☑ {item.tasks.filter((task) => !task.completed).length} tarefas</span><button onClick={(event) => { event.stopPropagation(); setCard(item); }}>Editar</button></footer></article>)}{!cardsFor(stage).length && <div className="column-empty">Nenhum lead neste filtro</div>}</div></div>)}<button className="add-column" onClick={addStage}>+ Nova etapa</button></section>
    </>}
    {stageEditor && <div className="modal-backdrop" onMouseDown={() => setStageEditor(null)}><form className="modal stage-modal" onSubmit={saveStage} onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">PERSONALIZAR ETAPA</span><h2>{stageEditor.id ? 'Editar etapa' : 'Nova etapa'}</h2></div><button type="button" onClick={() => setStageEditor(null)}>×</button></div><label>Nome da etapa<input autoFocus required value={stageEditor.name} onChange={(event) => setStageEditor({ ...stageEditor, name: event.target.value })} placeholder="Ex.: Reunião agendada" /></label><fieldset><legend>Cor de identificação</legend><div className="stage-colors">{['#E8E7FF','#DDF2FF','#FFF1D6','#FFE3DE','#E4F4EC','#F2E2F8','#E9E9E7','#DDEBE8'].map((color) => <button type="button" key={color} className={stageEditor.color === color ? 'active' : ''} style={{ background: color }} onClick={() => setStageEditor({ ...stageEditor, color })} aria-label={`Escolher cor ${color}`} />)}<label className="custom-color"><input type="color" value={stageEditor.color} onChange={(event) => setStageEditor({ ...stageEditor, color: event.target.value })} /><span>Cor personalizada</span></label></div></fieldset><div className="stage-preview"><span style={{ background: stageEditor.color }} /><div><small>PRÉVIA DA COLUNA</small><strong>{stageEditor.name || 'Nome da etapa'}</strong></div></div><div className="modal-actions"><button type="button" className="secondary" onClick={() => setStageEditor(null)}>Cancelar</button><button className="primary">{stageEditor.id ? 'Salvar alterações' : 'Criar etapa'}</button></div></form></div>}
    {card && <div className="modal-backdrop" onMouseDown={() => setCard(null)}><section className="modal card-modal" onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">CARTÃO DO LEAD</span><h2>{card.name || 'Editar cartão'}</h2></div><button onClick={() => setCard(null)}>×</button></div><form onSubmit={saveCard}><div className="form-grid"><label>Nome<input value={card.name} onChange={(event) => setCard({ ...card, name: event.target.value })} /></label><label>E-mail<input type="email" value={card.email} onChange={(event) => setCard({ ...card, email: event.target.value })} /></label><label>Telefone<input value={card.phone} onChange={(event) => setCard({ ...card, phone: event.target.value })} /></label><label>Empresa<input value={card.company} onChange={(event) => setCard({ ...card, company: event.target.value })} /></label></div><label>Observações<textarea rows={3} value={card.notes} onChange={(event) => setCard({ ...card, notes: event.target.value })} /></label><button className="primary save-card">Salvar alterações</button></form><section className="tasks-panel"><div className="tasks-title"><span className="eyebrow">TAREFAS</span><strong>{card.tasks.filter((task) => !task.completed).length} pendentes</strong></div><div className="task-list">{card.tasks.map((task) => <div className={task.completed ? 'task completed' : 'task'} key={task.id}><button onClick={() => toggleTask(task)}>{task.completed ? '✓' : ''}</button><span>{task.title}<small>{task.dueDate ? new Date(task.dueDate).toLocaleDateString('pt-BR') : 'Sem prazo'}</small></span><button onClick={() => deleteTask(task.id)}>×</button></div>)}</div><form className="add-task" onSubmit={addTask}><input value={taskTitle} onChange={(event) => setTaskTitle(event.target.value)} placeholder="Nova tarefa…" /><input type="date" value={taskDate} onChange={(event) => setTaskDate(event.target.value)} /><button className="secondary">Adicionar</button></form></section></section></div>}
  </div>;
}
