"use client";
import { useCallback, useEffect, useState } from "react";
type Product = { id: string; name: string; category: string; priceCents: number; color: string; active: boolean };
type Track = { id: string; name: string; description: string; active: boolean; nextTrackId: string | null; nextTrackName: string; items: { productId: string; position: number; product: Product }[] };
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export default function ProductTracksPanel({ flash }: { flash: (message: string) => void }) {
  const [tracks, setTracks] = useState<Track[]>([]); const [products, setProducts] = useState<Product[]>([]); const [canManage, setCanManage] = useState(false);
  const load = useCallback(async () => { const [t, p, me] = await Promise.all([fetch("/api/product-tracks"), fetch("/api/products"), fetch("/api/team/me")]); setTracks(await t.json()); setProducts(await p.json()); const profile = await me.json() as { role?: string }; setCanManage(profile.role === "manager" || profile.role === "admin"); }, []);
  useEffect(() => { load(); }, [load]);
  async function create() { const name = prompt("Nome da nova esteira")?.trim(); if (!name) return; const description = prompt("Objetivo da esteira", "") || ""; const response = await fetch("/api/product-tracks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description }) }); if (!response.ok) return flash("Não foi possível criar a esteira."); await load(); flash("Esteira criada."); }
  async function edit(track: Track) { const name = prompt("Nome da esteira", track.name)?.trim(); if (!name) return; const description = prompt("Objetivo da esteira", track.description) ?? track.description; await fetch(`/api/product-tracks/${track.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description }) }); await load(); flash("Esteira atualizada."); }
  async function remove(track: Track) { if (!confirm(`Excluir a esteira “${track.name}”?`)) return; await fetch(`/api/product-tracks/${track.id}`, { method: "DELETE" }); await load(); flash("Esteira excluída."); }
  async function connect(track: Track, nextTrackId: string) { const response = await fetch(`/api/product-tracks/${track.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ nextTrackId: nextTrackId || null }) }); if (!response.ok) return flash("Não foi possível conectar as esteiras."); await load(); flash(nextTrackId ? "Esteiras conectadas." : "Conexão removida."); }
  async function saveItems(track: Track, productIds: string[]) { const response = await fetch(`/api/product-tracks/${track.id}/items`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ productIds }) }); if (!response.ok) return flash("Não foi possível atualizar a sequência."); await load(); flash("Sequência da esteira atualizada."); }
  function move(track: Track, index: number, direction: -1 | 1) { const ids = track.items.map((item) => item.productId); const target = index + direction; if (target < 0 || target >= ids.length) return; [ids[index], ids[target]] = [ids[target], ids[index]]; saveItems(track, ids); }
  return <section className="commerce-screen"><header className="commerce-hero"><div><span className="eyebrow">ESTRATÉGIA DE OFERTAS</span><h2>Esteiras de produtos</h2><p>Organize a sequência, enxergue o potencial financeiro e conecte uma esteira à próxima.</p></div>{canManage && <button className="primary" onClick={create}>+ Nova esteira</button>}</header><div className="track-list">{tracks.map((track) => {
    const total = track.items.reduce((sum, item) => sum + item.product.priceCents, 0);
    return <article className="track-card" key={track.id}><header><div><small>ESTEIRA COMERCIAL</small><h3>{track.name}</h3><p>{track.description || "Sem descrição."}</p></div><div className="track-total"><small>VALOR DA ESTEIRA</small><strong>{money.format(total / 100)}</strong></div>{canManage && <div><button onClick={() => edit(track)}>Editar</button><button className="danger-text" onClick={() => remove(track)}>Excluir</button></div>}</header><div className="track-sequence">{track.items.map((item, index) => <div className="track-product" key={item.productId}><span className="track-number">{index + 1}</span><i style={{ background: item.product.color }} /><div><strong>{item.product.name}</strong><small>{money.format(item.product.priceCents / 100)} · {item.product.active ? "Ativo" : "Inativo"}</small></div>{canManage && <nav><button disabled={!index} onClick={() => move(track, index, -1)}>←</button><button disabled={index === track.items.length - 1} onClick={() => move(track, index, 1)}>→</button><button onClick={() => saveItems(track, track.items.filter((entry) => entry.productId !== item.productId).map((entry) => entry.productId))}>×</button></nav>}{index < track.items.length - 1 && <b>→</b>}</div>)}{!track.items.length && <div className="track-empty">Inclua produtos para montar a sequência.</div>}</div>{canManage && <div className="track-controls"><label className="track-add">Adicionar produto<select value="" onChange={(event) => event.target.value && saveItems(track, [...track.items.map((item) => item.productId), event.target.value])}><option value="">Escolha um produto…</option>{products.filter((product) => !track.items.some((item) => item.productId === product.id)).map((product) => <option key={product.id} value={product.id}>{product.name} · {money.format(product.priceCents / 100)}</option>)}</select></label><label className="track-connect">Próxima esteira<select value={track.nextTrackId || ""} onChange={(event) => connect(track, event.target.value)}><option value="">Encerrar nesta esteira</option>{tracks.filter((item) => item.id !== track.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>}{track.nextTrackName && <div className="track-link">Depois desta esteira → <strong>{track.nextTrackName}</strong></div>}</article>;
  })}{!tracks.length && <div className="commerce-empty">Nenhuma esteira cadastrada.</div>}</div></section>;
}
